### ISSUE TITLE
make requirement claim regex for code generic

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#11]
Currently code file tracing has `@llr` hardcoded in the regular expression to claim a requirement implementation.

Tracing should be permitted to arbitrary parent requirements (and test cases).

The regex should match anything such as `@\w+\s+REQ-...` which allows for flexibility in tracing. It would also have the side effect of catching spelling mistakes (if someone misspelled the project name in the claim, for example, reqtraq would say the requirement doesn't exist).

**Comment by aleb** [comment]
By requiring `@llr`, the code comments can mention requirements without linking the two, which is more flexible.
