### ISSUE TITLE
is lyx still supported?

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#22]
I see some commits indicating lyx is no longer supported, but lyx.go is still present, and is used when running `linkify`, for example.

**Comment by aleb** [comment]
We just migrated all the lyx files to md. The lyx support will be removed entirely (the linkify functionality).

**Comment by danieldanciu** [comment]
Chad, we just assumed that you guys also preferred to use MD, let us know
if that was not the case!

**Comment by cs01** [comment]
We use md, not lyx. I just wanted to make sure I understood why there were still lyx files in the code base after I saw some commits mentioning the removal of lyx support.
