### ISSUE TITLE
recommended workflow for editing requirements 

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#23]
I see there are quite a few doc types in `config_ddln.go`, so I imagine you have lots of requirements and requirement files, and relationships to manage. 

How do you make changes to these docs? Do you have a workflow to change a doc and quickly/immediately see what its rendered output looks like?

I have been trying to think of my preferred workflow for making these types of changes (admittedly I have not been doing much actual requirement writing). I think it would be something like a browser split into three vertical panes:
1. A nice visual graph of all requirements 
1. The rendered markdown when a requirement in the graph is clicked
1. The source of that same markdown file that can be modified and have its changes reflected in the graph and rendered markdown in Pane 2

I'm curious if you have something like this/think it would be useful.

**Comment by danieldanciu** [comment]
Hey Chad -

Most of us are using Atom (https://atom.io/) to edit requirement files, as
it supports a nice preview while editing. Many other editors support this,
but Atom has it out of the box. This would correspond to points 2. and 3.
in your email above.
For the visual graph of all the requirements we were toying with the idea
of adding reqtraq support for it, but in the end decided this was not that
useful.

Daniel

**Comment by cs01** [comment]
Thanks for the feedback. I have markdown integration with my text editor, but was interested in these other features  because LaTeX/mathjax is not rendered in my text editor (nor is the UML flow chart if that's added), and the parent/child tree is not easily explorable.
