### ISSUE TITLE
add travis build integration

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#3]
add travis ci and unit tests

https://docs.travis-ci.com/user/languages/go/

**Comment by cs01** [comment]
@daedaleanai @aleb is there any way you can enable travis integration for daedaleanai/reqtraq? I enabled it for zeeaero/reqtraq, but it would be better if it were on daedaleanai/reqtraq so that we would know if pull requests pass unit tests before merging.

**Comment by aleb** [comment]
Done. See 177a31880daee9d5db448699082bd3be853f9d33
