### ISSUE TITLE
require leading zeroes in requirement id

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#6]
reqtraq allows requirement names such as `REQ-0-DAED-SYS-001` followed by `REQ-0-DAED-SYS-2`, but they should require the same number of leading zeroes.

The `nextid` command correctly prints `REQ-0-DAED-SYS-003`

Source code which traces up to `REQ-0-DAED-SYS-002` results in an error because it requires the leading zeroes when resolving the trace.

**Comment by mattofak** [comment]
It would be more ideal to have it not care how many leading zeros there
are. Possibly by normalizing it to having none. Otherwise what happens when
you go from -999 to -1000 and you only have room for three digits?

**Comment by cs01** [comment]
Good point. Either way it should not allow a mixture of the two. I think requiring no leading zeros or requiring the same number of digits in all requirements would be fine. The "no leading zeros" rule would make the transition from 999 to 1000 easier, as you mentioned.

**Comment by danieldanciu** [comment]
I assume the leading zeroes format comes from a time when these labels were
frequently printed on paper and it was easier to recognize the patter if it
always had the same length. I think/hope that we'll never get to a
situation where the requirement number exceeds 999, but if that is a
concern, I agree with Matt that simply removing the leading zeroes is best.

**Comment by aleb** [comment]
The minor breakage to our internal documents should be easy to fix, no problem. If `go test` passes and `reqtraq web` can show the bottom-up and top-down reports, it's good.
