### ISSUE TITLE
proper way to handle multiple config_xxx.go files

### ISSUE THREAD

**Issue by cs01** [daedaleanai/reqtraq#7]
It's unclear to me what the best way to make our own config is. Should we add a flag to specify which config to use, or create a branch and rename the file to `config_zee.go` or something else?

**Comment by danieldanciu** [comment]
I think the easiest would be to create your own `config_zee.go` next to `config_ddln.go` and mark it with a build tag, e.g. `zae'. Then edit `config_ddln.go` in line 3 and delete the `!ddln` tag.

The drawback is that you'll have to specify the build tag on the command line each time you compile:
  `go build -tags zae`

If that becomes too annoying, creating your own branch is also an option.

**Comment by aleb** [comment]
`go test` might fail when using a different config file. We could move the configuration from a go file to a json file and keep it duplicated wherever we have a certdocs directory. Then we could specify which json config to use for each test where it matters. The config-reading logic would get a bit more complex. An advantage would be that when reqtraq is updated, it will still work with repositories which have not been updated yet.

**Comment by danieldanciu** [comment]
go test supports the -tags flag, so it won't fail. Our initial thought was
that we'd all share the same branch and you guys would create a
config_zee.go next to config_ddln.go, with a different build tag.

Alex prefers a json config specified via a flag. Either way works fine.
